# Generated by Django 4.1.3 on 2023-04-10 18:15

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_date_op', models.CharField(default='', help_text='Please put in event date.', max_length=50)),
                ('Event_title', models.CharField(default='', help_text='Please put in a exciting title for the event!', max_length=200)),
                ('Event_description', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Please use title case formatting only', max_length=50)),
                ('cover_description', models.TextField(default='', max_length=400)),
                ('description', models.TextField(default='', max_length=5000)),
                ('cover_image', models.ImageField(default='', upload_to=main.models.path_academics_title)),
                ('image_1', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_academics_title)),
                ('image_2', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_academics_title)),
                ('image_3', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_academics_title)),
                ('youtube_video', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicsPageTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_date_op', models.CharField(default='', help_text='Please put in event date.', max_length=50)),
                ('Event_title', models.CharField(default='', help_text='Please put in a exciting title for the event!', max_length=200)),
                ('Event_description', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Please use title case formatting only', max_length=50)),
                ('cover_description', models.TextField(default='', max_length=400)),
                ('description', models.TextField(default='', max_length=5000)),
                ('cover_image', models.ImageField(default='', upload_to=main.models.path_service_title)),
                ('image_1', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_2', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_3', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_4', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_5', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_6', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_7', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('youtube_video', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_description', models.TextField(default='', help_text='Provide an introduction on the home page!')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('middle_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('picture', models.ImageField(upload_to='personalInformation/')),
                ('picture_background_removed', models.ImageField(default='', upload_to='personalInformation/')),
                ('hobbies', models.TextField(default='', help_text='Please separate them by a comma.')),
                ('interests', models.TextField(default='', help_text='Please separate them by a comma.')),
                ('skills', models.TextField(default='', help_text='Please separate them by a comma.')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Please use title case formatting only', max_length=50)),
                ('cover_description', models.TextField(default='', max_length=400)),
                ('description', models.TextField(default='', max_length=5000)),
                ('references', models.TextField(default='', max_length=1000)),
                ('cover_image', models.ImageField(default='', upload_to=main.models.path_project_title)),
                ('image_1', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title)),
                ('image_2', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title)),
                ('image_3', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title)),
                ('image_4', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title)),
                ('image_5', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title)),
                ('image_6', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title)),
                ('image_7', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title)),
                ('youtube_video', models.CharField(default='', max_length=40)),
                ('discipline_of_work', models.TextField(default='', help_text='Please separate them by a comma.')),
            ],
        ),
    ]
