# Generated by Django 4.1.3 on 2023-04-10 18:46

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf_file',
            field=models.FileField(blank=True, default='', null=True, upload_to=main.models.path_project_title),
        ),
    ]
