# Generated by Django 4.1.3 on 2023-04-07 07:00

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsPageTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_date_op', models.CharField(default='', help_text='Please put in event date.', max_length=50)),
                ('Event_title', models.CharField(default='', help_text='Please put in a exciting title for the event!', max_length=200)),
                ('Event_description', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image_1',
            field=models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_4',
            field=models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_5',
            field=models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_6',
            field=models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_7',
            field=models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_project_title),
        ),
    ]
