# Generated by Django 4.1.3 on 2022-11-02 07:50

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_person_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='', max_length=500)),
                ('references', models.TextField(default='', max_length=1000)),
                ('cover_image', models.ImageField(default='', upload_to=main.models.upload_path_project)),
                ('image_1', models.ImageField(default='', upload_to=main.models.upload_path_project)),
                ('image_2', models.ImageField(default='', upload_to=main.models.upload_path_project)),
                ('image_3', models.ImageField(default='', upload_to=main.models.upload_path_project)),
                ('image_4', models.ImageField(default='', upload_to=main.models.upload_path_project)),
                ('image_5', models.ImageField(default='', upload_to=main.models.upload_path_project)),
                ('image_6', models.ImageField(default='', upload_to=main.models.upload_path_project)),
                ('image_7', models.ImageField(default='', upload_to=main.models.upload_path_project)),
                ('youtube_video', models.CharField(default='', max_length=40)),
                ('discipline_of_work', models.TextField(default='', help_text='Please separate them by a comma.')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(upload_to='personalInformation/'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture_background_removed',
            field=models.ImageField(default='', upload_to='personalInformation/'),
        ),
    ]
