# Generated by Django 4.1.3 on 2023-04-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_academicspagetimelineevent_alter_project_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_description',
            field=models.TextField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
    ]
