# Generated by Django 4.1.3 on 2023-04-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_pdf_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pdf_file',
            new_name='PDF_file',
        ),
    ]
