# Generated by Django 4.1.3 on 2023-04-07 08:50

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_project_cover_description_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', help_text='Please use title case formatting only', max_length=50)),
                ('cover_description', models.TextField(default='', max_length=400)),
                ('description', models.TextField(default='', max_length=5000)),
                ('cover_image', models.ImageField(default='', upload_to=main.models.path_service_title)),
                ('image_1', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_2', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_3', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_4', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_5', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_6', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('image_7', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_service_title)),
                ('youtube_video', models.CharField(default='', max_length=40)),
            ],
        ),
    ]
