# Generated by Django 4.1.3 on 2023-04-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_youtube_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicachievement',
            name='youtube_video',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='communityservice',
            name='youtube_video',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
    ]
