# Generated by Django 4.1.3 on 2023-04-11 07:17

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_academicachievement_youtube_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('World_Image', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_travel_title)),
                ('India_Image', models.ImageField(blank=True, default='', null=True, upload_to=main.models.path_travel_title)),
            ],
        ),
    ]
